// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmZIQNckafShCMWsQbT5a75rLiXKroYOc',
    appId: '1:71707683184:web:0aa938545f64691eaa87b5',
    messagingSenderId: '71707683184',
    projectId: 'news-app-9bc60',
    authDomain: 'news-app-9bc60.firebaseapp.com',
    storageBucket: 'news-app-9bc60.appspot.com',
    measurementId: 'G-VLB6CFQ6W7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2AqiMEiXDnu-ADYddPC8ohfbXVvko0iE',
    appId: '1:71707683184:android:5445bbb4081ca6a7aa87b5',
    messagingSenderId: '71707683184',
    projectId: 'news-app-9bc60',
    storageBucket: 'news-app-9bc60.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAj8UW4I1U1TLBmCEXlQ-ROzoivNbZXCv0',
    appId: '1:71707683184:ios:3dfe6146b7afec00aa87b5',
    messagingSenderId: '71707683184',
    projectId: 'news-app-9bc60',
    storageBucket: 'news-app-9bc60.appspot.com',
    iosClientId: '71707683184-80vd4kcdj6do1e4u5a9qta6sb0q2v46a.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookingHotel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAj8UW4I1U1TLBmCEXlQ-ROzoivNbZXCv0',
    appId: '1:71707683184:ios:6375b3c65e5e8144aa87b5',
    messagingSenderId: '71707683184',
    projectId: 'news-app-9bc60',
    storageBucket: 'news-app-9bc60.appspot.com',
    iosClientId: '71707683184-i4pupjd8p1ene78e960snu90rdn82aes.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookingHotel.RunnerTests',
  );
}
